# Librarie's used are :

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# Question - 1 (Importing the dataset from sklearn)

In [3]:
from sklearn.datasets import load_digits
dig = load_digits()

# Question - 2  {Splitting the dataset into training and testing sets}

In [4]:
X = dig.data
y = dig.target

In [28]:
print(X.shape)
print(y.shape)

(1797, 64)
(1797,)


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)
X_train.shape

(1078, 64)

# Question - 3

In [7]:
from sklearn.svm import SVC

## 1) For Linear Kernel

In [9]:
lin = SVC(kernel='linear')
lin.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

### Predictions

In [11]:
linPredict = lin.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix, classification_report

In [13]:
lin_CM = confusion_matrix(y_test, linPredict)
print('Confusion Matrix with linear kernel')
print(lin_CM)

Confusion Matrix with linear kernel
[[67  0  0  0  0  0  0  0  0  0]
 [ 0 71  0  0  1  0  0  0  0  0]
 [ 0  0 66  0  0  0  0  0  0  0]
 [ 0  0  0 69  0  1  0  0  1  0]
 [ 0  0  0  0 78  0  0  0  0  0]
 [ 0  0  0  0  0 81  0  1  0  1]
 [ 0  0  0  0  0  0 69  0  0  0]
 [ 0  0  0  0  0  0  0 70  0  1]
 [ 0  3  0  0  0  1  0  0 61  0]
 [ 0  0  0  1  1  0  0  0  0 75]]


In [15]:
lin_CR = classification_report(y_test, linPredict)
print('Classification report taking linear kernel :')
print(lin_CR)

Classification report taking linear kernel :
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        67
          1       0.96      0.99      0.97        72
          2       1.00      1.00      1.00        66
          3       0.99      0.97      0.98        71
          4       0.97      1.00      0.99        78
          5       0.98      0.98      0.98        83
          6       1.00      1.00      1.00        69
          7       0.99      0.99      0.99        71
          8       0.98      0.94      0.96        65
          9       0.97      0.97      0.97        77

avg / total       0.98      0.98      0.98       719



## 2) For Poly Kernel

In [16]:
poly = SVC(kernel='poly')
poly.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

### predictions

In [17]:
polyPredict = poly.predict(X_test)

In [18]:
poly_CM = confusion_matrix(y_test, polyPredict)
print('Confusion Matrix with poly kernel :')
print(poly_CM)

Confusion Matrix with poly kernel :
[[67  0  0  0  0  0  0  0  0  0]
 [ 0 72  0  0  0  0  0  0  0  0]
 [ 0  0 66  0  0  0  0  0  0  0]
 [ 0  0  0 69  0  1  0  0  1  0]
 [ 0  0  0  0 78  0  0  0  0  0]
 [ 0  0  0  0  0 82  0  0  0  1]
 [ 0  0  0  0  0  0 69  0  0  0]
 [ 0  0  0  0  0  0  0 70  0  1]
 [ 0  1  0  0  0  0  0  0 64  0]
 [ 0  0  0  1  0  0  0  1  0 75]]


In [19]:
poly_CR = classification_report(y_test, polyPredict)
print('Classification report taking poly kernel :')
print(poly_CR)

Classification report taking poly kernel :
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        67
          1       0.99      1.00      0.99        72
          2       1.00      1.00      1.00        66
          3       0.99      0.97      0.98        71
          4       1.00      1.00      1.00        78
          5       0.99      0.99      0.99        83
          6       1.00      1.00      1.00        69
          7       0.99      0.99      0.99        71
          8       0.98      0.98      0.98        65
          9       0.97      0.97      0.97        77

avg / total       0.99      0.99      0.99       719



## 3) For Sigmoid Kernel

In [20]:
sigmoid = SVC(kernel='sigmoid')
sigmoid.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

### Predictions

In [21]:
sigPredict = sigmoid.predict(X_test)

In [22]:
sig_CM = confusion_matrix(y_test, sigPredict)
print('Confusion Matrix with Sigmoid kernel :')
print(sig_CM)

Confusion Matrix with Sigmoid kernel :
[[ 0  0  0  1  0  0 66  0  0  0]
 [ 0  0  0  0  0  0 72  0  0  0]
 [ 0  0  0  0  0  0 66  0  0  0]
 [ 0  0  0  1  0  0 70  0  0  0]
 [ 0  0  0  0  0  0 78  0  0  0]
 [ 0  0  0  0  0  0 83  0  0  0]
 [ 0  0  0  0  0  0 69  0  0  0]
 [ 0  0  0  2  0  0 69  0  0  0]
 [ 0  0  0  0  0  0 65  0  0  0]
 [ 0  0  0  0  0  0 77  0  0  0]]


In [23]:
sig_CR = classification_report(y_test, sigPredict)
print('Classification report taking Sigmoid kernel :')
print(sig_CR)

Classification report taking Sigmoid kernel :
             precision    recall  f1-score   support

          0       0.00      0.00      0.00        67
          1       0.00      0.00      0.00        72
          2       0.00      0.00      0.00        66
          3       0.25      0.01      0.03        71
          4       0.00      0.00      0.00        78
          5       0.00      0.00      0.00        83
          6       0.10      1.00      0.18        69
          7       0.00      0.00      0.00        71
          8       0.00      0.00      0.00        65
          9       0.00      0.00      0.00        77

avg / total       0.03      0.10      0.02       719



G:\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


## 1) For Guassian Kernel

In [24]:
gauss = SVC(kernel='rbf')
gauss.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

### Predictions

In [25]:
gausPredict = gauss.predict(X_test)

In [26]:
gaus_CM = confusion_matrix(y_test, gausPredict)
print('Confusion Matrix with gaussian kernel :')
print(gaus_CM)

Confusion Matrix with gaussian kernel :
[[32  0  0 35  0  0  0  0  0  0]
 [ 0 33  0 39  0  0  0  0  0  0]
 [ 0  0 44 22  0  0  0  0  0  0]
 [ 0  0  0 71  0  0  0  0  0  0]
 [ 0  0  0 58 20  0  0  0  0  0]
 [ 0  0  0 83  0  0  0  0  0  0]
 [ 0  0  0 16  0  0 53  0  0  0]
 [ 0  0  0 32  0  0  0 39  0  0]
 [ 0  0  0 35  0  0  0  0 30  0]
 [ 0  0  0 66  0  0  0  0  0 11]]


In [27]:
gaus_CR = classification_report(y_test, gausPredict)
print('Classification report taking gaussian kernel :')
print(gaus_CR)

Classification report taking gaussian kernel :
             precision    recall  f1-score   support

          0       1.00      0.48      0.65        67
          1       1.00      0.46      0.63        72
          2       1.00      0.67      0.80        66
          3       0.16      1.00      0.27        71
          4       1.00      0.26      0.41        78
          5       0.00      0.00      0.00        83
          6       1.00      0.77      0.87        69
          7       1.00      0.55      0.71        71
          8       1.00      0.46      0.63        65
          9       1.00      0.14      0.25        77

avg / total       0.80      0.46      0.50       719



G:\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
